import axios from "axios";
axios.defaults.withCredentials = true;
export const API_URL_Enterprise = "http://localhost:3000/api/enterprise";
export const API_URL_User = "http://localhost:3000/api/user";
export const API_URL_Admin = "http://localhost:3000/api/admin";
export const API_URL_Title = "http://localhost:3000/api/title";
export const API_URL_Capacitation = "http://localhost:3000/api/capacitation";
export const API_URL_Category = "http://localhost:3000/api/category";
export const API_URL_Course = "http://localhost:3000/api/course";
export const API_URL_Developer = "http://localhost:3000/api/developer";
